try {
    let a = 2 + c;
} catch (error) {
    console.log(error);
}

console.log("Teste");